version: '3'
services:
  pomablockchainapiweb-service:
    image: pomablockchainapiweb
    build:
      context: .
      dockerfile: POMABlockchain.Web/Dockerfile
    depends_on:
      - mongo
    environment:
      Mongo: "mongodb://127.0.0.1:57017/?connectTimeoutMS=2000"    
    
  mongo:
    container_name: "mongopoma"
    image: mongo
    ports:
      - "57017:27017"
  

