version: '3'
services:
  pomablockchainapiweb-service:
    image: pomablockchainapiweb
    build:
      context: .
      dockerfile: POMABlockchain.Api.WebApp/Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8022:80"
             
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
   
  


