version: '3'
services:
  pomablockchainapiweb-service:
    image: pomablockchainapiweb
    build:
      context: .
      dockerfile: POMABlockchain.Web/Dockerfile
    depends_on:
      - mongo
   
  mongo:
    container_name: "mongopoma"
    image: mongo
    ports:
      - "57017:27017"
   
  


